### ISSUE TITLE
A C# version SliceView

### ISSUE THREAD

**Issue by yoda0612** [haesleinhuepf/stackview#23]
Hi, I am very interested in your StackView. I applied your demo tiff and made a very simple C# version SliceViewer. I think the performace of using C# would be better. 
https://github.com/yoda0612/SliceViewer

**Comment by haesleinhuepf** [comment]
Awesome! Very cool @yoda0612 ! Is there a way for using it within Jupyter / from Python? It would be great to combine both technologies

**Comment by yoda0612** [comment]
@haesleinhuepf I found a solution that let Jupyter can use C#. How it seems that it doesn't support create Windows interface. The SliceViewer I created is a standlong application, that's why the performace is better.
