### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by bpavie** [haesleinhuepf/stackview#28]
Hi 

I tried to run it on our university jupyter lab via ondemands,
I installed a conda environement and stackivew via `conda install -c conda-forge stackview` and ran the following example

```
import stackview

import numpy as np
from skimage.io import imread
from skimage.filters import gaussian

image = imread('https://github.com/haesleinhuepf/stackview/blob/main/docs/data/Haase_MRT_tfl3d1.tif?raw=true', plugin='tifffile')
stackview.slice(image, continuous_update=True)
```

which give me the following error message (with no extra information)
```
Error displaying widget: model not found
```
Is there something else that need to be installed ? Would you have any tips to identify the issue?

Note that it works fine locally for me via vscode

**Comment by haesleinhuepf** [comment]
Hi @bpavie ,

we've had similar issues on our cluster:
https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/issues/5

... and couldn't resolve it. I presume it is related to a version mismatch of the Jupyter Hub and your kernel environment. If you find out anything, I'd love to learn more!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Hi Benjamin @bpavie ,

I may have found a solution. Within Jupyter Hub, open a console and install stackview using the `--user` command:
```
pip install stackview --user
```

Do not activate any environment before installing it. It is important to install it in the same space where Jupyter is installed.

Let me know if this works!

Best,
Robert

**Comment by haesleinhuepf** [comment]
I presume this has been solved.
