### ISSUE TITLE
Can stackview work in VS Code?

### ISSUE THREAD

**Issue by yiqunma** [haesleinhuepf/stackview#35]
So I do most of my work in VS Code. I tried this tool in a notebook in VS Code but the widget did not render. Are there known ways to make this great tool work in VS Code? TIA

**Comment by Suyash-Naik** [comment]
Hi @yiqunma I use vs code for my notebooks and stackview works for me. Did you perhaps try changing the way your plots are displayed in the cells?

**Comment by haesleinhuepf** [comment]
Hi @yiqunma ,

as you solved the issue, can you us tell how? Maybe others would profit from the solution posted here 😉

Thanks!

Best,
Robert

**Comment by yiqunma** [comment]
Embarrassingly, rebooting my PC did the magic 😆
