### ISSUE TITLE
Issue with voila link

### ISSUE THREAD

**Issue by smith6jt-cop** [haesleinhuepf/stackview#40]
Hello,

I experienced an error:
![image](https://github.com/haesleinhuepf/stackview/assets/73438963/1d846fbc-3919-47d9-87bc-322eb3a6f41e)

**Comment by haesleinhuepf** [comment]
Hi @smith6jt-cop ,

cam you explain where you clicked to receive this error? The voila link in the readme leads to the voila websiy, not to Binder...

Thanks!

**Comment by smith6jt-cop** [comment]
Please disregard.  I clicked the Binder link on Voila thinking it was an example of stackview, but it is not.

**Comment by haesleinhuepf** [comment]
Ah ok cool. I'm closing this. 

Best,
Robert
